development: &default
  adapter: postgresql
  encoding: unicode
  database: hypertube_development
  pool: 5
  username: postgres
  password:
  host: db

test:
  <<: *default
  database: hypertube_test

production:
  <<: *default
  database: hypertube_production
