development: &default
  adapter: postgresql
  database: Hypertube_development
  encoding: SQL_ASCII
  host: localhost
  min_messages: warning
  password: load
  pool: 5
  timeout: 5000
  username: heavy

docker:
  adapter: postgresql
  encoding: unicode
  database: Hypertube_docker
  pool: 5
  username: postgres
  password:
  host: db

test:
  <<: *default
  database: Hypertube_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: hypertube_production
