# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d0b7a34b833abb6f5b8eb526e7afaf5c62dcb9c2dbb148dbf50d494aa2668c528df2c99d256d7eb916dbdcab079bfaee48fcaffbeff02ee5e926406e9cd4efb

test:
  secret_key_base: a4b544d6fd4359ba048d25d760dcdfd4947e2f976709e2250f4a666a89592e70b75ca1bcf7684057cc3d79297c52f368f676722cd533d9ca2e74208f2845cae4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
